# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
